name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++ cmake make

    - name: Compile main program
      run: g++ -std=c++17 -Wall -Wextra -o my_program ConsoleApplication2/ConsoleApplication2/ConsoleApplication2.cpp

    - name: Compile and run tests
      run: |
        cd Tests
        g++ -std=c++17 -Wall -Wextra -o test_program test.cpp -I$(pwd)/../Catch
        ./test_program
