name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++ cmake make

    - name: Compile main application
      run: g++ -std=c++17 -Wall -Wextra -o my_program ConsoleApplication2/ConsoleApplication2/ConsoleApplication2.cpp


    - name: Create build directory for tests
      run: mkdir -p build


    - name: Configure the project with CMake
      run: cmake -S . -B build

    - name: Build the tests
      run: cmake --build build

    - name: Run unit tests
      run: ./build/tests  
